namespace Tehom
open System
open Nu

(*
    To tl;dr the point of the project:
    Create a horror text game with a systemic support for body horror to then infuse it with text generation.

    Main goals for the foreseeable future:
    * Add good way of mass-loading entities from some form of config file, currently thinking yaml
    * Add some rudimentary display of context around player entity
    * Add some form of text input that gets processed as actions, rudimentary string comparison would do
    * Make it possible to move player entity from room 1 to room 2
*)

module TehomID =

    type TehomID =
        | ID of string
        | GUID of Guid
    with
        static member empty = ID ""
        static member guid = GUID (Guid.NewGuid())

    type AttributeID = AttributeID of TehomID
    with
        static member unwrap (AttributeID x) = x

    type ActorID = ActorID of TehomID
    with
        static member unwrap (ActorID x) = x

    type AbilityID = AbilityID of TehomID
    with
        static member unwrap (AbilityID x) = x

    type AbilityGroupID = AbilityGroupID of TehomID
    with
        static member unwrap (AbilityGroupID x) = x

    type ActionID = ActionID of TehomID
    with
        static member unwrap (ActionID x) = x

open TehomID

module Screens =

    // Main screens of the game, put here temporarily.
    type Screens =
        | Title
        | SaveLoad
        | Exploration
        | Combat

module GUI =

    // Rough idea for GUI, main elements are input box and scene (current block of text shown)
    type GUI =
        | InputBox
        | Scene
        | Stats
        | OtherElements

module Ability =
    open TehomID

    type Value =
        | Free
        | Cost of int
        | Gain of int

    type Power =
        | Weak
        | Normal of int
        | Godlike

    type Level = uint32 * uint32 * float

    type Ability = {
        AbilityGroup: AbilityGroupID

        Power: Power

        Initiative: Value
        Focus: Value
        Time: Value

//        ChanceToFail: int
        Levels: Set<Level>


    } with
        static member default' = {
            AbilityGroup = AbilityGroupID TehomID.empty
            Power = Weak
            Initiative = Free
            Focus = Free
            Time = Free
            Levels = Set.empty
        }

    // Limits what
    // sort of actions are allowed for each level, i.e. rudimentary brain will disallow talking even with a functioning mouth
    // TODO: come up with better names
    // Main point of thinking is to distinguish 'dead' entities from 'alive', as well as animalistic entities,
    // from ones of higher reasoning and ones of beyond-human reasoning capabilities
    // 'alive' entity always has at least one free functioning task-processing limb, be it brain, processor or whatever else

    type SenseLevel =
        | Self
        | SameParent
        | Parent
        | Grandparent
        | Anylevel

    // TODO: come up with what metric should be those based on


module Time =
    // Time is a 360-based clock and a day counter.
    // Day is composed of 12 hours, each separated into 30 minutes
    // Each hour is named astrologically.
    // Point is to avoid AM/PM/Military stuff and also distance the world.
    [<Measure>]
    type Minute

    [<Measure>]
    type Hour

    type Time = Time of int<Minute>

    type Hours =
        | Aries = 0
        | Taurus = 1
        | Gemini = 2
        | Cancer = 3
        | Leo = 4
        | Virgo = 5
        | Libra = 6
        | Scorpio = 7
        | Sagittarius = 8
        | Capricorn = 9
        | Aquarius = 10
        | Pisces = 11
        | End = 12

    type Minutes =
        | Begin = 0
        | End = 30


    // Most basic time-consuming action costs a minute.

module Trait =

    // Some string describing the object, whether defined as is, or to be generated on demand based on entity context.
    type GeneratableString =
        | String of string
        | Autogenerated
        | Inapplicable

    // Combination of object's player-seen name and description.
    type DescriptionTrait = {
        Name: GeneratableString
        Description: GeneratableString
    }

    // Come up how to unite this with contains as only something that has volume can contain things.
    type Volume =
        | SumOfContained
        | Volume of int64
        | Infinite
        | Inapplicable

    // Any physical object is supposed to have both internal and external volume,
    // to allow for objects that are bigger on the inside i.e.
    type VolumeTrait = {
        Internal: Volume
        External: Volume
    }

    // Could be useful for physical objects to have mass.
    type MassTrait = {
        Mass: int
    }

    type HealthTrait = {
        Health: int
        MaxHealth: int
        Regeneration: int
    }



module Actor =
    open TehomID
    open Trait

    type Actor = {

        Volume: VolumeTrait option
        Mass: MassTrait option
        Health: HealthTrait option
        Abilities: Set<AbilityID>

    } with

        static member default' = {
            Volume = None
            Mass = None
            Health = None
            Abilities = Set.empty
        }


    // Signifies physical attachment, i.e. finger is attached to palm, door is attached to wall.
    // Trait that determines what other entities this entity is attached to.
    // The main issue is that these relations go both ways and can be influenced from either side,
    // i.e. to use the example from 'Attached': finger can be separated from the hand by a sword,
    // hand can be separated from the finger by a sword, either action result is supposed to be the same.

    type Attached =
        | Strongly
        | WithForce of int
        | Weakly




    // Trait that lists other entities parent entity is composed of.
    // It is not necessarily physical, as player party consists of every member of the party.
    // Point of this list is so that we can get slices of this composition based on children traits,
    // i.e. if we apply filter of HasAbility CanMove _ we can get creature's entire locomotion system.
    type Composed =
        | Simple
        // So at to define ability of parent entity to control its child entities,
        // I want to define cohesion of the entity agglomeration
        // Low cohesion -> actions are less of orders and more of suggestions
        // i.e. low cohesion party of NPCs will disobey player character
        | Controls of int
    with
        static member default' =
            Controls 100

        static member multiply composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Simple
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (x * x' / 100)

        static member max composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Controls x'
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (max x x')

    type Composition = Composition of Map<ActorID, Composed>
    with
        static member unwrap (Composition x) = x


    type Limb = Limb of List<ActorID * Composed>
    with
        static member unwrap (Limb x) = x

        static member default' = Limb List.empty

        static member composed (Limb limb) =
            limb
            |> List.map snd
            |> List.fold Composed.multiply Composed.default'

        static member fromComposition (Composition composition : Composition) : Set<Limb> =
            composition
            |> Map.toSeq
            |> Seq.map (fun x -> Limb [x])
            |> Set.ofSeq

        static member children (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (parent, _) = List.head limb
            match Map.tryFind parent compositions with
            | None -> Set.empty
            | Some composition ->
                composition
                |> Limb.fromComposition
                |> Set.map (Limb.unwrap >> (fun list -> List.append list limb) >> Limb)

        static member parents (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (child, _) = List.head limb
            compositions
            |> Map.filter (fun _ ->
                Composition.unwrap >> Map.containsKey child
            )
            |> Map.map (fun parent (Composition composition) ->
                Map.find child composition
            )
            |> Map.fold (fun set parent composed ->
                Set.add (Limb ([parent, composed] @ limb)) set
            ) Set.empty

        static member grandChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.children compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        static member grandParents (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.parents compositions)
            |> Set.unionMany

        static member siblings (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        // TODO: remake these recursive functions so they
        // TODO: accumulate limbs correctly and don't record the same ones over and over
        static member internal childrenN (compositions : Map<ActorID, Composition>) (level : UInt32)
            (limb : Limb) : Set<Limb> =
            let rec childrenN (i: UInt32) limb =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.children compositions
                    |> Set.map (childrenN (i - 1u))
                    |> Set.unionMany

            childrenN level limb

        static member internal parentsN (compositions : Map<ActorID, Composition>) (level : uint32)
            (limb : Limb) : Set<Limb> =
            let rec parentsN (i: uint32) limb  =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.parents compositions
                    |> Set.map (parentsN (i - 1u))
                    |> Set.unionMany

            parentsN level limb

        static member allChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            let rec allchildren limb =
                let children = Limb.children compositions limb

                children
                |> Set.map allchildren
                |> Set.unionMany
                |> Set.union children

            allchildren limb

        static member allChildrenByID (compositions : Map<ActorID, Composition>) (actorID : ActorID) : Set<Limb> =
            Limb [actorID, Composed.default']
            |> Limb.allChildren compositions

        static member custom (compositions : Map<ActorID, Composition>)
            (up: uint32) (down: uint32) (limb : Limb) : Set<Limb> =

            let parents = if up <= 0u then id else Set.map (Limb.parentsN compositions up) >> Set.unionMany
            let children = if down <= 0u then id else Set.map (Limb.childrenN compositions down) >> Set.unionMany

//            let limb = [Limb.unwrap limb |> List.head] |> Limb

            Set.ofList [limb]
            |> parents
            |> children


    type Attachment = Attached * Set<ActorID>

module Action =
    open TehomID
    //
    type Action = {
        Whatever: uint32
        Order: List<AbilityGroupID>
    }
    with
        static member default' = {
            Whatever = 0u
            Order = List.empty
        }

module Actions =

    open TehomID
    open Actor
    open Ability
    open Action

    // needs objects
    (*
    Verb -> Set<Action>
    Action -> Set<Ability * Limb * Composed>
    Ability -> Set<Object>
    *)

    type Choice = {
        Action: ActionID
        Ability: AbilityID
        Limb: Limb
        Object: ActorID
    }
    with
        static member default' = {
            Action = ActionID TehomID.empty
            Ability = AbilityID TehomID.empty
            Limb = Limb.default'
            Object = ActorID TehomID.empty
        }


    // should be map of actorabilities -> objects
    type Choices = Set<Choice>

    let choices (subject: ActorID) (actors: Map<ActorID, Actor>) (compositions: Map<ActorID, Composition>)
        (abilities: Map<AbilityID, Ability>) (actions: Map<ActionID, Action>) =
            // filtering by limbs presupposed here, when composition is created.
        let limbs = Limb.allChildrenByID compositions subject

        let objects abilityID limb =
            if Map.containsKey abilityID abilities then
                let levels = abilities[abilityID].Levels
                levels
                |> Set.map (fun (up, down, _) ->
                    Limb.custom compositions up down limb
                    |> Set.map (Limb.unwrap >> List.head >> fst)
                )
                |> Set.unionMany
            else
                Set.empty

        let actions abilityID =
            if Map.containsKey abilityID abilities then

                let abilityGroup = abilities[abilityID].AbilityGroup

                actions
                |> Map.filter (fun _ value ->
                    List.contains abilityGroup value.Order
                )
                |> Map.keys
                |> Set.ofSeq
            else
               Set.empty

        let abilities limb =
            let abilities actorID =
                if Map.containsKey actorID actors then
                    actors[actorID].Abilities
                else
                    Set.empty
            limb
            |> Limb.unwrap
            |> List.head
            |> fst
            |> abilities

        limbs
        |> Set.map (fun limb -> { Choice.default' with Limb = limb })

        |> Set.map (fun choice ->
            Set.map (fun ability -> { choice with Ability = ability }) (abilities choice.Limb)
        )
        |> Set.unionMany

        |> Set.map (fun choice ->
            Set.map (fun verb -> { choice with Action = verb }) (actions choice.Ability)
        )
        |> Set.unionMany

        |> Set.map (fun choice ->
            Set.map (fun object -> { choice with Object = object }) (objects choice.Ability choice.Limb)
        )
        |> Set.unionMany



    type ChoiceLevel =
        | FailedAtSubject of string
        | FailedAtAction of string
        | FailedAtAbility of string
        | FailedAtLimb of string
        | FailedAtObject of string

    type ChoiceResult = Result<Choices, ChoiceLevel>

    let filterChoices (subject: ActorID) (action : ActionID option) (ability : AbilityID option)
        (limb : Limb Option) (object : ActorID option) (choices : Choices) : ChoiceResult =

        let (|Empty|_|) a = if Set.isEmpty a then Some () else None

        let filterBy compare = function
            | None -> id
            | Some a -> Set.filter (fun (b : Choice) -> a === compare b)

        let actionFilter = filterBy (function { Action = x } -> x) action
        let abilityFilter = filterBy (function { Ability = x } -> x) ability
        let limbFilter = filterBy (function { Limb = x } -> x) limb
        let objectFilter = filterBy (function { Object = x } -> x) object

        match choices with
            | Empty -> Error (FailedAtSubject $"%A{subject}")
            | choices ->
        match actionFilter choices with
            | Empty -> Error (FailedAtAction $"%A{action.Value}")
            | choices ->
        match abilityFilter choices with
            | Empty -> Error (FailedAtAbility $"%A{ability.Value}")
            | choices ->
        match limbFilter choices with
            | Empty -> Error (FailedAtLimb $"%A{limb}")
            | choices ->
        match objectFilter choices with
            | Empty -> Error (FailedAtObject $"%A{object.Value}")
            | choices -> Ok choices

    let subject = ActorID (ID "cat")
    let action = ActionID (ID "look")
    let object = ActorID (ID "key")

    let tempFilter = filterChoices (subject) (Some action) (None) (None) (Some object)

    (*
    possibilities

    TODO: make action
    TODO: filter actorAbiltiies by abilities by action
    TODO: filter actorAbilities by composed
    TODO: pick best for a think             <- per action

    handling

    *)

    let whatever =
        let getChildrenSet actor (compositions: Map<TehomID, Composition>) =
            let (Composition composition) = compositions[actor]
            composition
            |> Map.keys
            |> Set.ofSeq

        let getParentsSet actor compositions =
            compositions
            |> Map.values
            |> Seq.map Map.keys
            |> Seq.filter (Seq.contains actor)
            |> Seq.map Set.ofSeq
            |> Set.unionMany

        let concat func1 func2 actor (compositions: Map<TehomID, Composition>) =
            let func1 actor = func1 actor compositions
            let func2 actor = func2 actor compositions

            func1 actor
            |> Set.map func2
            |> Set.unionMany
        ()

    // Rough list of actions 'alive' entities should be capable of, each action should require a certain 'Ability'.
    type EntityActions =
        | Look
        | Go

        | Use
        | Equip
        | UnEquip
        | Take
        | Drop
        | Give

        | Attack
        | Say

    // Will be reworked, rough draft of actions
    // Somewhere in this module or later there would happen mapping between UI-sent actions and actions player entity does.
    type PlayerActions =
        | Wait
        | Look
        | Explore
        | Go

        | Self
        | Party

        | Use
        | Equip
        | UnEquip
        | Take
        | Drop
        | Give

        | Attack
        | Say

(*
    Horror situations that should be possible in the simulation:
    * Corpses coming alive;
    * Monsters with arrays of limbs;
    * You traversing a large enough creature from the inside a la James Bartley.
    * Parasites traversing your body;
    * Your limbs 'dying' while still attached to your body;
    * Your limb growing multiple eyes that you can see through;
    * Your limb growing multiple eyes that you can not see through;     <- some concept of ownership or control is definitely needed
    * Your limb leaving you to become its own creature that can be either hostile or friendly to player;
    * Various supernatural things like telekinesis or teleportation;
*)