namespace Tehom
open System
open Nu

module TehomID =

    type TehomID =
        | ID of string
        | GUID of Guid
    with
        static member empty = ID ""
        static member guid = GUID (Guid.NewGuid())

    type AttributeID = AttributeID of TehomID
    with
        static member unwrap (AttributeID x) = x

    type ActorID = ActorID of TehomID
    with
        static member unwrap (ActorID x) = x

    type AbilityID = AbilityID of TehomID
    with
        static member unwrap (AbilityID x) = x

    type AbilityGroupID = AbilityGroupID of TehomID
    with
        static member unwrap (AbilityGroupID x) = x

    type ActionID = ActionID of TehomID
    with
        static member unwrap (ActionID x) = x

open TehomID


module Ability =
    open TehomID

    type Value =
        | Free
        | Cost of int
        | Gain of int

    type Power =
        | Weak
        | Normal of int
        | Godlike

    type Level = uint32 * uint32 * float

    type Ability = {
        AbilityGroup: AbilityGroupID

        Power: Power

        Initiative: Value
        Focus: Value
        Time: Value

//        ChanceToFail: int
        Levels: Set<Level>


    } with
        static member default' = {
            AbilityGroup = AbilityGroupID TehomID.empty
            Power = Weak
            Initiative = Free
            Focus = Free
            Time = Free
            Levels = Set.empty
        }

    // Limits what
    // sort of actions are allowed for each level, i.e. rudimentary brain will disallow talking even with a functioning mouth
    // TODO: come up with better names
    // Main point of thinking is to distinguish 'dead' entities from 'alive', as well as animalistic entities,
    // from ones of higher reasoning and ones of beyond-human reasoning capabilities
    // 'alive' entity always has at least one free functioning task-processing limb, be it brain, processor or whatever else

    type SenseLevel =
        | Self
        | SameParent
        | Parent
        | Grandparent
        | Anylevel

    // TODO: come up with what metric should be those based on





    // Most basic time-consuming action costs a minute.

module Trait =

    // Some string describing the object, whether defined as is, or to be generated on demand based on entity context.
    type GeneratableString =
        | String of string
        | Autogenerated
        | Inapplicable

    // Combination of object's player-seen name and description.
    type DescriptionTrait = {
        Name: GeneratableString
        Description: GeneratableString
    }

    // Come up how to unite this with contains as only something that has volume can contain things.
    type Volume =
        | SumOfContained
        | Volume of int64
        | Infinite
        | Inapplicable

    // Any physical object is supposed to have both internal and external volume,
    // to allow for objects that are bigger on the inside i.e.
    type VolumeTrait = {
        Internal: Volume
        External: Volume
    }

    // Could be useful for physical objects to have mass.
    type MassTrait = {
        Mass: int
    }

    type HealthTrait = {
        Health: int
        MaxHealth: int
        Regeneration: int
    }



module Actor =
    open TehomID
    open Trait

    type Actor = {

        Volume: VolumeTrait option
        Mass: MassTrait option
        Health: HealthTrait option
        Abilities: Set<AbilityID>

    } with

        static member default' = {
            Volume = None
            Mass = None
            Health = None
            Abilities = Set.empty
        }



    type Attached =
        | Strongly
        | WithForce of int
        | Weakly



    type Composed =
        | Simple

        | Controls of int
    with
        static member default' =
            Controls 100

        static member multiply composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Simple
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (x * x' / 100)

        static member max composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Controls x'
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (max x x')

    type Composition = Composition of Map<ActorID, Composed>
    with
        static member unwrap (Composition x) = x


    type Limb = Limb of List<ActorID * Composed>
    with
        static member unwrap (Limb x) = x

        static member default' = Limb List.empty

        static member composed (Limb limb) =
            limb
            |> List.map snd
            |> List.fold Composed.multiply Composed.default'

        static member fromComposition (Composition composition : Composition) : Set<Limb> =
            composition
            |> Map.toSeq
            |> Seq.map (fun x -> Limb [x])
            |> Set.ofSeq

        static member children (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (parent, _) = List.head limb
            match Map.tryFind parent compositions with
            | None -> Set.empty
            | Some composition ->
                composition
                |> Limb.fromComposition
                |> Set.map (Limb.unwrap >> (fun list -> List.append list limb) >> Limb)

        static member parents (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (child, _) = List.head limb
            compositions
            |> Map.filter (fun _ ->
                Composition.unwrap >> Map.containsKey child
            )
            |> Map.map (fun parent (Composition composition) ->
                Map.find child composition
            )
            |> Map.fold (fun set parent composed ->
                Set.add (Limb ([parent, composed] @ limb)) set
            ) Set.empty

        static member grandChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.children compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        static member grandParents (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.parents compositions)
            |> Set.unionMany

        static member siblings (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        // TODO: remake these recursive functions so they
        // TODO: accumulate limbs correctly and don't record the same ones over and over
        static member internal childrenN (compositions : Map<ActorID, Composition>) (level : UInt32)
            (limb : Limb) : Set<Limb> =
            let rec childrenN (i: UInt32) limb =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.children compositions
                    |> Set.map (childrenN (i - 1u))
                    |> Set.unionMany

            childrenN level limb

        static member internal parentsN (compositions : Map<ActorID, Composition>) (level : uint32)
            (limb : Limb) : Set<Limb> =
            let rec parentsN (i: uint32) limb  =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.parents compositions
                    |> Set.map (parentsN (i - 1u))
                    |> Set.unionMany

            parentsN level limb

        static member allChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            let rec allchildren limb =
                let children = Limb.children compositions limb

                children
                |> Set.map allchildren
                |> Set.unionMany
                |> Set.union children

            allchildren limb

        static member allChildrenByID (compositions : Map<ActorID, Composition>) (actorID : ActorID) : Set<Limb> =
            Limb [actorID, Composed.default']
            |> Limb.allChildren compositions

        static member custom (compositions : Map<ActorID, Composition>)
            (up: uint32) (down: uint32) (limb : Limb) : Set<Limb> =

            let parents = if up <= 0u then id else Set.map (Limb.parentsN compositions up) >> Set.unionMany
            let children = if down <= 0u then id else Set.map (Limb.childrenN compositions down) >> Set.unionMany

//            let limb = [Limb.unwrap limb |> List.head] |> Limb

            Set.ofList [limb]
            |> parents
            |> children


    type Attachment = Attached * Set<ActorID>

module Action =
    open TehomID
    //
    type Action = {
        Whatever: uint32
        Order: List<AbilityGroupID>
    }
    with
        static member default' = {
            Whatever = 0u
            Order = List.empty
        }