actors:

- parent: ""
  name: ""
  description: ""
  guid:
    - Consists
    - of
    - Several
    - IDs
  abilities:
    - ability: has
      subtype: whatever
      value: 0
    - ability: many
      subtype: whatever
      value: 1
    - ability: abilities
      subtype: whatever
      value: 2

- parent: ""
  name: ""
  description: ""
  guid:
    - Consists
    - of
    - Several
    - IDs
  abilities:
    - ability: has
      subtype: whatever
      value: 0
    - ability: many
      subtype: whatever
      value: 1
    - ability: abilities
      subtype: whatever
      value: 2