namespace Tehom

#if OLD

open TehomID
open Actor
open Trait
open Ability
open Action

module TehomActors =


module TehomID =

    type TehomID =
        | ID of string
        | GUID of Guid
    with
        static member empty = ID ""
        static member guid = GUID (Guid.NewGuid())

    type AttributeID = AttributeID of TehomID
    with
        static member unwrap (AttributeID x) = x

    type ActorID = ActorID of TehomID
    with
        static member unwrap (ActorID x) = x

    type AbilityID = AbilityID of TehomID
    with
        static member unwrap (AbilityID x) = x

    type AbilityGroupID = AbilityGroupID of TehomID
    with
        static member unwrap (AbilityGroupID x) = x

    type ActionID = ActionID of TehomID
    with
        static member unwrap (ActionID x) = x

open TehomID


module Ability =
    open TehomID

    type Value =
        | Free
        | Cost of int
        | Gain of int

    type Power =
        | Weak
        | Normal of int
        | Godlike

    type Level = uint32 * uint32 * float

    type Ability = {
        AbilityGroup: AbilityGroupID

        Power: Power

        Initiative: Value
        Focus: Value
        Time: Value

//        ChanceToFail: int
        Levels: Set<Level>


    } with
        static member default' = {
            AbilityGroup = AbilityGroupID TehomID.empty
            Power = Weak
            Initiative = Free
            Focus = Free
            Time = Free
            Levels = Set.empty
        }

    // Limits what
    // sort of actions are allowed for each level, i.e. rudimentary brain will disallow talking even with a functioning mouth
    // TODO: come up with better names
    // Main point of thinking is to distinguish 'dead' entities from 'alive', as well as animalistic entities,
    // from ones of higher reasoning and ones of beyond-human reasoning capabilities
    // 'alive' entity always has at least one free functioning task-processing limb, be it brain, processor or whatever else

    type SenseLevel =
        | Self
        | SameParent
        | Parent
        | Grandparent
        | Anylevel

    // TODO: come up with what metric should be those based on





    // Most basic time-consuming action costs a minute.

module Trait =

    // Some string describing the object, whether defined as is, or to be generated on demand based on entity context.
    type GeneratableString =
        | String of string
        | Autogenerated
        | Inapplicable

    // Combination of object's player-seen name and description.
    type DescriptionTrait = {
        Name: GeneratableString
        Description: GeneratableString
    }

    // Come up how to unite this with contains as only something that has volume can contain things.
    type Volume =
        | SumOfContained
        | Volume of int64
        | Infinite
        | Inapplicable

    // Any physical object is supposed to have both internal and external volume,
    // to allow for objects that are bigger on the inside i.e.
    type VolumeTrait = {
        Internal: Volume
        External: Volume
    }

    // Could be useful for physical objects to have mass.
    type MassTrait = {
        Mass: int
    }

    type HealthTrait = {
        Health: int
        MaxHealth: int
        Regeneration: int
    }



module Actor =
    open TehomID
    open Trait

    type Actor = {

        Volume: VolumeTrait option
        Mass: MassTrait option
        Health: HealthTrait option
        Abilities: Set<AbilityID>

    } with

        static member default' = {
            Volume = None
            Mass = None
            Health = None
            Abilities = Set.empty
        }



    type Attached =
        | Strongly
        | WithForce of int
        | Weakly



    type Composed =
        | Simple

        | Controls of int
    with
        static member default' =
            Controls 100

        static member multiply composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Simple
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (x * x' / 100)

        static member max composed composed' =
            match composed with
            | Simple ->
                match composed' with
                | Simple -> Simple
                | Controls x' -> Controls x'
            | Controls x ->
                match composed' with
                | Simple -> Controls x
                | Controls x' -> Controls (max x x')

    type Composition = Composition of Map<ActorID, Composed>
    with
        static member unwrap (Composition x) = x


    type Limb = Limb of List<ActorID * Composed>
    with
        static member unwrap (Limb x) = x

        static member default' = Limb List.empty

        static member composed (Limb limb) =
            limb
            |> List.map snd
            |> List.fold Composed.multiply Composed.default'

        static member fromComposition (Composition composition : Composition) : Set<Limb> =
            composition
            |> Map.toSeq
            |> Seq.map (fun x -> Limb [x])
            |> Set.ofSeq

        static member children (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (parent, _) = List.head limb
            match Map.tryFind parent compositions with
            | None -> Set.empty
            | Some composition ->
                composition
                |> Limb.fromComposition
                |> Set.map (Limb.unwrap >> (fun list -> List.append list limb) >> Limb)

        static member parents (compositions : Map<ActorID, Composition>) (Limb limb : Limb) : Set<Limb> =
            let (child, _) = List.head limb
            compositions
            |> Map.filter (fun _ ->
                Composition.unwrap >> Map.containsKey child
            )
            |> Map.map (fun parent (Composition composition) ->
                Map.find child composition
            )
            |> Map.fold (fun set parent composed ->
                Set.add (Limb ([parent, composed] @ limb)) set
            ) Set.empty

        static member grandChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.children compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        static member grandParents (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.parents compositions)
            |> Set.unionMany

        static member siblings (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            limb
            |> Limb.parents compositions
            |> Set.map (Limb.children compositions)
            |> Set.unionMany

        // TODO: remake these recursive functions so they
        // TODO: accumulate limbs correctly and don't record the same ones over and over
        static member internal childrenN (compositions : Map<ActorID, Composition>) (level : UInt32)
            (limb : Limb) : Set<Limb> =
            let rec childrenN (i: UInt32) limb =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.children compositions
                    |> Set.map (childrenN (i - 1u))
                    |> Set.unionMany

            childrenN level limb

        static member internal parentsN (compositions : Map<ActorID, Composition>) (level : uint32)
            (limb : Limb) : Set<Limb> =
            let rec parentsN (i: uint32) limb  =
                if (i = 0u) then Set.ofList [limb]
                else
                    limb
                    |> Limb.parents compositions
                    |> Set.map (parentsN (i - 1u))
                    |> Set.unionMany

            parentsN level limb

        static member allChildren (compositions : Map<ActorID, Composition>) (limb : Limb) : Set<Limb> =
            let rec allchildren limb =
                let children = Limb.children compositions limb

                children
                |> Set.map allchildren
                |> Set.unionMany
                |> Set.union children

            allchildren limb

        static member allChildrenByID (compositions : Map<ActorID, Composition>) (actorID : ActorID) : Set<Limb> =
            Limb [actorID, Composed.default']
            |> Limb.allChildren compositions

        static member custom (compositions : Map<ActorID, Composition>)
            (up: uint32) (down: uint32) (limb : Limb) : Set<Limb> =

            let parents = if up <= 0u then id else Set.map (Limb.parentsN compositions up) >> Set.unionMany
            let children = if down <= 0u then id else Set.map (Limb.childrenN compositions down) >> Set.unionMany

//            let limb = [Limb.unwrap limb |> List.head] |> Limb

            Set.ofList [limb]
            |> parents
            |> children


    type Attachment = Attached * Set<ActorID>

module Action =
    open TehomID
    //
    type Action = {
        Whatever: uint32
        Order: List<AbilityGroupID>
    }
    with
        static member default' = {
            Whatever = 0u
            Order = List.empty
        }

    type Actors = {

        Descriptions: Map<TehomID, DescriptionTrait>

        Actors: Map<ActorID, Actor>
        Compositions: Map<ActorID, Composition>

        Abilities: Map<AbilityID, Ability>

        Actions: Map<ActionID, Action>

        Attachments: Set<Attachment>

        // TODO: root entities, maybe

    }
    with
        static member empty = {
            Descriptions = Map.empty

            Actors = Map.empty
            Compositions = Map.empty

            Abilities = Map.empty
            Actions = Map.empty

            Attachments = Set.empty
        }

        static member addDefault =

            let cat (gameplay: Actors) =

                let ``id think/animal`` = AbilityID (ID "think\\animal")
                let ``action think/animal`` = {
                    Ability.default' with
                        AbilityGroup = AbilityGroupID (ID "think")
                        Initiative = Gain 2
                        Focus = Gain 4
                        Levels = Set.ofList [
                            0u, 0u, 1.0
                        ]
                    }

                let ``id see/cat`` = AbilityID (ID "see\\cat")
                let ``action see/cat`` = {
                    Ability.default' with
                        AbilityGroup = AbilityGroupID (ID "see")
                        Initiative = Cost 1
                        Focus = Cost 1
                        Levels = Set.ofList [
                            2u, 2u, 2.0   // look at siblings' children
                            2u, 1u, 1.0   // look at siblings
                            2u, 0u, 1.0   // look at parent
                            1u, 0u, 0.0   // look at self
                            1u, 1u, 0.0   // look at children
                            1u, 2u, 1.0   // look at grandchildren
                            1u, 3u, 2.0   // look at great grandchildren
                        ]
                    }

                let actions actions =
                    actions
                    |> Map.toList
                    |> List.append [
                        ``id think/animal``, ``action think/animal``
                        ``id see/cat``, ``action see/cat``
                    ]
                    |> Map.ofList


                let ``id cat/brain`` = ID "cat\\brain"
                let ``actor cat/brain`` = { Actor.default' with Abilities = Set.ofList [ ``id think/animal`` ] }

                let ``id cat/ears`` = ID "cat\\ears"
                let ``actor cat/ears`` = { Actor.default' with Abilities = Set.ofList [ AbilityID (ID "hear\\cat") ] }

                let ``id cat/eyes`` = ID "cat\\eyes"
                let ``actor cat/eyes`` = { Actor.default' with Abilities = Set.ofList [ ``id see/cat`` ] }

                let ``id cat/legBackRight`` = ID "cat\\legBackRight"
                let ``id cat/legBackLeft`` = ID "cat\\legBackLeft"

                let ``actor cat/legBack`` = { Actor.default' with Abilities = Set.ofList [ AbilityID (ID "walk\\cat") ] }
                let ``id cat/legFrontLeft`` = ID "cat\\legFrontLeft"

                let ``id cat/legFrontRight`` = ID "cat\\legFrontRight"
                let ``actor cat/legFront`` = {
                    Actor.default' with
                        Abilities = Set.ofList [
                            AbilityID (ID "walk\\cat")
                            AbilityID (ID "attack\\cat\\paw")
                        ]
                }

                let ``id cat/mouth`` = ID "cat\\mouth"
                let ``actor cat/mouth`` = {
                    Actor.default' with
                        Abilities = Set.ofList [
                            AbilityID (ID "eat\\cat")
                            AbilityID (ID "grab\\cat\\mouth")
                            AbilityID (ID "attack\\cat\\mouth")
                        ]
                }

                let ``id cat/skin`` = ID "cat\\skin"
                let ``id cat/skull`` = ID "cat\\skull"

                let ``id cat/tail`` = ID "cat\\tail"
                let ``actor cat/tail`` = { Actor.default' with Abilities = Set.ofList [ AbilityID (ID "balance\\cat") ] }

                let ``id cat/torso`` = ID "cat\\torso"
                let ``actor cat/torso`` = { Actor.default' with Abilities = Set.ofList [ AbilityID (ID "balance\\cat") ] }

                let ``id cat`` = ID "cat"
                let ``actor cat`` : Actor = Actor.default'
                let ``description cat`` : DescriptionTrait = {
                    Name = String "Cat the NPC"
                    Description = String "Simple NPC for testing NPC creation."
                }

                let ``composition cat`` : Composition = Composition (
                    Map.ofList [
                        ActorID ``id cat/brain``, Controls 100
                        ActorID ``id cat/ears``, Controls 100
                        ActorID ``id cat/eyes``, Controls 100
                        ActorID ``id cat/legBackRight``, Controls 100
                        ActorID ``id cat/legBackLeft``, Controls 100
                        ActorID ``id cat/legFrontLeft``, Controls 100
                        ActorID ``id cat/legFrontRight``, Controls 100
                        ActorID ``id cat/mouth``, Controls 100
                        ActorID ``id cat/skin``, Controls 100
                        ActorID ``id cat/skull``, Controls 100
                        ActorID ``id cat/tail``, Controls 100
                        ActorID ``id cat/torso``, Controls 100
                    ]
                )

                let descriptions =
                    Map.add ``id cat`` ``description cat``

                let actors =
                    Map.toList
                    >> List.append [
                        ActorID ``id cat``, ``actor cat``
                        ActorID ``id cat/brain``, ``actor cat/brain``
                        ActorID ``id cat/ears``, ``actor cat/ears``
                        ActorID ``id cat/eyes``, ``actor cat/eyes``
                        ActorID ``id cat/legBackRight``, ``actor cat/legBack``
                        ActorID ``id cat/legBackLeft``, ``actor cat/legBack``
                        ActorID ``id cat/legFrontLeft``, ``actor cat/legFront``
                        ActorID ``id cat/legFrontRight``, ``actor cat/legFront``
                        ActorID ``id cat/mouth``, ``actor cat/mouth``
                        ActorID ``id cat/tail``, ``actor cat/tail``
                        ActorID ``id cat/torso``, ``actor cat/torso``
                    ]
                    >> Map.ofList

                let composition =
                    Map.add (ActorID ``id cat``) ``composition cat``

                { gameplay with
                    Descriptions = descriptions gameplay.Descriptions
                    Abilities = actions gameplay.Abilities
                    Actors = actors gameplay.Actors
                    Compositions = composition gameplay.Compositions
                }


            let table (gameplay: Actors) =

                let ``id table`` = ID "table"
                let ``actor table`` = Actor.default'
                let ``description table`` = {
                    Name = String "Table McTableface"
                    Description = String "A normal wooden table for testing non-alive entities."
                }
                let ``composition table`` = Composition (
                    Map.ofList [
                        ActorID (ID "table\\surface"), Simple
                        ActorID (ID "table\\leg1"), Simple
                        ActorID (ID "table\\leg2"), Simple
                        ActorID (ID "table\\leg3"), Simple
                        ActorID (ID "table\\leg4"), Simple
                    ]
                )

                let descriptions =
                    Map.add ``id table`` ``description table``

                let actors =
                    Map.add (ActorID ``id table``) ``actor table``

                let composition =
                    Map.add (ActorID ``id table``) ``composition table``

                { gameplay with
                    Descriptions = descriptions gameplay.Descriptions
                    Actors = actors gameplay.Actors
                    Compositions = composition gameplay.Compositions
                }


            let world (gameplay: Actors) =

                let ``id think`` = ActionID (ID "think")
                let ``action think`` = {
                    Action.default' with
                        Order = [
                            AbilityGroupID (ID "think")
                        ]
                }

                let ``id look`` = ActionID (ID "look")
                let ``action look`` = {
                    Action.default' with
                        Order = [
                            AbilityGroupID (ID "think")
                            AbilityGroupID (ID "see")
                        ]
                }

                let actions =
                    Map.add ``id look`` ``action look``
                    >> Map.add ``id think`` ``action think``

                let ``id key`` = ID "key"
                let ``actor key`` = Actor.default'
                let ``description key`` = {
                    Name = String "Shiny key"
                    Description = String "A key that shines and opens doors."
                }

                let ``id dungeon/north`` = ID "dungeon\\north"
                let ``actor dungeon/north`` = Actor.default'
                let ``description dungeon/north`` = {
                    Name = String "Northern Room"
                    Description = String "The room up north, dark and cold."
                }
                let ``composition dungeon/north`` = Composition (
                    Map.ofList [
                        ActorID (ID "cat"), Simple
                        ActorID ``id key``, Simple
                    ]
                )

                let ``id dungeon/south`` = ID "dungeon\\south"
                let ``actor dungeon/south`` = Actor.default'
                let ``description dungeon/south`` = {
                    Name = String "Southern Room"
                    Description = String "The room down south, lit and warm."
                }
                let ``composition dungeon/south`` = Composition (
                    Map.ofSeq [
                        ActorID (ID "table"), Simple
                    ]
                )

                let ``id dungeon`` = ID "dungeon"
                let ``composition dungeon`` : Composition = Composition (
                    Map.ofSeq [
                        ActorID ``id dungeon/north``, Simple
                        ActorID ``id dungeon/south``, Simple
                    ]
                )

                let ``id tehom`` = ID "tehom"
                let ``actor tehom`` = Actor.default'
                let ``description tehom`` = {
                    Name = String "Tehom"
                    Description = String "The world, needlessly cruel."
                }
                let ``composition tehom`` = Composition (
                    Map.ofSeq [
                        ActorID ``id dungeon``, Simple
                    ]
                )

                let descriptions =
                    Map.add ``id key`` ``description key``
                    >> Map.add ``id dungeon/north`` ``description dungeon/north``
                    >> Map.add ``id dungeon/south`` ``description dungeon/south``
                    >> Map.add ``id tehom`` ``description tehom``

                let actors =
                    Map.add (ActorID ``id key``) ``actor key``
                    >> Map.add (ActorID ``id dungeon/north``) ``actor dungeon/north``
                    >> Map.add (ActorID ``id dungeon/south``) ``actor dungeon/south``
                    >> Map.add (ActorID ``id tehom``) ``actor tehom``

                let composition =
                    Map.add (ActorID ``id dungeon``) ``composition dungeon``
                    >> Map.add (ActorID ``id dungeon/north``) ``composition dungeon/north``
                    >> Map.add (ActorID ``id dungeon/south``) ``composition dungeon/south``
                    >> Map.add (ActorID ``id tehom``) ``composition tehom``

                { gameplay with
                    Descriptions = descriptions gameplay.Descriptions
                    Actors = actors gameplay.Actors
                    Compositions = composition gameplay.Compositions
                    Actions = actions gameplay.Actions
                }

            cat >> table >> world
(*

    Entities can be looked from two angles, structural composition, of what consists of what:
    Table is composed of: table top, 4 table legs.

    And physical composition:
    * Table top
    * 4 table legs, each attached to table top



    Alive entities are a little more complex.

    What is a cat?

    Alive entities can be also looked at from two angles:

    Physical composition:
    * torso
    * 2 front legs, 2 back legs attached to torso
    * tail attached to torso
    * head attached to torso
        head of course can also be split:
        * skull
        * two eyes attached to skull
        * brain attached to skull
        * skin attached to skull

    Another way to look at the cat is through systems which correspond to its abilities,
    which are retrieved through filtering structural composition for its abilities:
    Cat has:
    * Nervous system -- Filter by CanThink -> brain
    * Sensory system -- Filter by CanSense -> Eyes, nose, ears, skin, etc
    * Locomotion system -- Filter by CanMove -> Legs, paws, tail (?), ???
    * Manipulation system -- Filter by CanGrab -> paws, mouth
    * Talking system -- Filter by CanTalk -> mouth, lungs (?)
    * Attack system - Filter by IsWeapon -> paws, mouth
    New systems can be added later as needed, as it's literally just a filter over the composed entity.

*)

type TehomActors = TehomActors.Actors


module TehomChoices =

    open TehomID
    open Actor
    open Ability
    open Action
    open TehomActors

    // needs objects
    (*
    Verb -> Set<Action>
    Action -> Set<Ability * Limb * Composed>
    Ability -> Set<Object>
    *)

    type Choice = {
        Action: ActionID
        Ability: AbilityID
        Limb: Limb
        Object: ActorID
    }
    with
        static member empty = {
            Action = ActionID TehomID.empty
            Ability = AbilityID TehomID.empty
            Limb = Limb.default'
            Object = ActorID TehomID.empty
        }


    // should be map of actorabilities -> objects
    type Choices = Choices of Set<Choice>
    with
        static member unwrap (Choices choices) = choices
        static member choices (subject: ActorID) (tehomActors : TehomActors) =

            let { Actors = actors; Compositions = compositions; Abilities = abilities; Actions = actions } = tehomActors

                // filtering by limbs presupposed here, when composition is created.
            let limbs = Limb.allChildrenByID compositions subject

            let objects abilityID limb =
                if Map.containsKey abilityID abilities then
                    let levels = abilities[abilityID].Levels
                    levels
                    |> Set.map (fun (up, down, _) ->
                        Limb.custom compositions up down limb
                        |> Set.map (Limb.unwrap >> List.head >> fst)
                    )
                    |> Set.unionMany
                else
                    Set.empty

            let actions abilityID =
                if Map.containsKey abilityID abilities then

                    let abilityGroup = abilities[abilityID].AbilityGroup

                    actions
                    |> Map.filter (fun _ value ->
                        List.contains abilityGroup value.Order
                    )
                    |> Map.keys
                    |> Set.ofSeq
                else
                   Set.empty

            let abilities limb =
                let abilities actorID =
                    if Map.containsKey actorID actors then
                        actors[actorID].Abilities
                    else
                        Set.empty
                limb
                |> Limb.unwrap
                |> List.head
                |> fst
                |> abilities

            limbs
            |> Set.map (fun limb -> { Choice.empty with Limb = limb })

            |> Set.map (fun choice ->
                Set.map (fun ability -> { choice with Ability = ability }) (abilities choice.Limb)
            )
            |> Set.unionMany

            |> Set.map (fun choice ->
                Set.map (fun verb -> { choice with Action = verb }) (actions choice.Ability)
            )
            |> Set.unionMany

            |> Set.map (fun choice ->
                Set.map (fun object -> { choice with Object = object }) (objects choice.Ability choice.Limb)
            )
            |> Set.unionMany
            |> Choices

        static member filter (subject: ActorID) (action : ActionID option) (ability : AbilityID option)
            (limb : Limb Option) (object : ActorID option) (Choices choices : Choices) =

            let (|Empty|_|) a = if Set.isEmpty a then Some () else None

            let filterBy compare = function
                | None -> id
                | Some a -> Set.filter (fun (b : Choice) -> a === compare b)

            let actionFilter = filterBy (function { Action = x } -> x) action
            let abilityFilter = filterBy (function { Ability = x } -> x) ability
            let limbFilter = filterBy (function { Limb = x } -> x) limb
            let objectFilter = filterBy (function { Object = x } -> x) object

            match choices with
                | Empty -> Error $"Failed at subject %A{subject}"
                | choices ->
            match actionFilter choices with
                | Empty -> Error $"Failed at action %A{action.Value}"
                | choices ->
            match abilityFilter choices with
                | Empty -> Error $"Failed at ability %A{ability.Value}"
                | choices ->
            match limbFilter choices with
                | Empty -> Error $"Failed at limb %A{limb}"
                | choices ->
            match objectFilter choices with
                | Empty -> Error $"Failed at object %A{object.Value}"
                | choices -> Ok (Choices choices)
        static member best (Choices choices : Choices) = Set.maxElement choices

    let subject = ActorID (ID "cat")
    let action = ActionID (ID "look")
    let object = ActorID (ID "key")


    (*
    possibilities

    TODO: make action
    TODO: filter actorAbiltiies by abilities by action
    TODO: filter actorAbilities by composed
    TODO: pick best for a think             <- per action

    handling

    *)

    let whatever =
        let getChildrenSet actor (compositions: Map<TehomID, Composition>) =
            let (Composition composition) = compositions[actor]
            composition
            |> Map.keys
            |> Set.ofSeq

        let getParentsSet actor compositions =
            compositions
            |> Map.values
            |> Seq.map Map.keys
            |> Seq.filter (Seq.contains actor)
            |> Seq.map Set.ofSeq
            |> Set.unionMany

        let concat func1 func2 actor (compositions: Map<TehomID, Composition>) =
            let func1 actor = func1 actor compositions
            let func2 actor = func2 actor compositions

            func1 actor
            |> Set.map func2
            |> Set.unionMany
        ()

    // Rough list of actions 'alive' entities should be capable of, each action should require a certain 'Ability'.
    type EntityActions =
        | Look
        | Go

        | Use
        | Equip
        | UnEquip
        | Take
        | Drop
        | Give

        | Attack
        | Say

    // Will be reworked, rough draft of actions
    // Somewhere in this module or later there would happen mapping between UI-sent actions and actions player entity does.
    type PlayerActions =
        | Wait
        | Look
        | Explore
        | Go

        | Self
        | Party

        | Use
        | Equip
        | UnEquip
        | Take
        | Drop
        | Give

        | Attack
        | Say

type TehomChoice = TehomChoices.Choice
type TehomChoices = TehomChoices.Choices


#endif