<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <Import Project="../../Nu/Nu.Common.targets" />

    <ItemGroup>
        <None Include="Assets\*" />
        <None Include="Assets\*\*" />
        <None Update="Assets\Default\SlugDemo.svg" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\Noto-COLRv1.ttf" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\Tiger.svg" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\Lobster-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\Allura-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\Anton-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
        <None Update="Assets\Default\LibreBaskerville.ttf" CopyToOutputDirectory="PreserveNewest" />
        <Compile Include="SlugDemoContours.fs" />
        <Compile Include="SlugDemoShared.fs" />
        <Compile Include="Simulants.fs" />
        <Compile Include="SlugDemoProjectionSupport.fs" />
        <Compile Include="SlugDemoVectorSupport.fs" />
        <Compile Include="SlugDemoTextSupport.fs" />
        <Compile Include="SlugDemoHudComputeSupport.fs" />
        <Compile Include="SlugDemoEmoji.fs" />
        <Compile Include="SlugDemoPbrIbl.fs" />
        <Compile Include="SlugDemoAnimatedGlyphs.fs" />
        <Compile Include="SlugDemoLayerEffects.fs" />
        <Compile Include="SlugDemoMorphing.fs" />
        <Compile Include="SlugDemoProjection2d.fs" />
        <Compile Include="SlugDemoProjection3d.fs" />
        <Compile Include="SlugDemoGradients.fs" />
        <Compile Include="SlugDemoMasking.fs" />
        <Compile Include="SlugDemoHud.fs" />
        <Compile Include="SlugDemoAnimatedHud.fs" />
        <Compile Include="SlugDemoShapesCompositeShapes.fs" />
        <Compile Include="SlugDemoMixedScenes.fs" />
        <Compile Include="SlugDemoAnimatedScenes.fs" />
        <Compile Include="SlugDemoObjects3d.fs" />
        <Compile Include="SlugDemoSvg.fs" />
        <Compile Include="SlugDemoText.fs" />
        <Compile Include="SlugDemoMixedText.fs" />
        <Compile Include="SlugDemoTextEffects.fs" />
        <Compile Include="SlugDemoTextAlongPath.fs" />
        <Compile Include="SlugDemoComputeShaders.fs" />
        <Compile Include="SlugDemo.fs" />
        <Compile Include="SlugDemoPlugin.fs" />
        <Compile Include="Program.fs" />
        <None Include="AssetGraph.nuag" />
        <None Include="Overlayer.nuol" />
        <None Include="App.config" />
    </ItemGroup>

</Project>
